import {NextRequest,NextResponse} from "next/server";
type Line={main?:boolean;active?:boolean;is_off?:boolean;cost?:number|string;line?:number|string};type Book={id:number;lines?:Line[]};type Selection={selection?:string;books?:Book[]};type Offer={market_id?:number;selections?:Selection[]};type Quote={line:number;odds:number;book:string;side:"Over"|"Under";main:boolean};type Market={line:number;overOdds:number|null;underOdds:number|null;overBook:string|null;underBook:string|null};type PitcherOdds={markets:Record<string,Market|null>;alternateStrikeouts:{line:number;overOdds:number|null;book:string|null}[]};
const marketKeys:Record<number,string>={285:"SO",408:"BB",290:"ER",404:"HITS",405:"OUTS"},allowedBooks:Record<number,string>={10:"FanDuel",12:"DraftKings",19:"BetMGM",60:"Novig",68:"Kalshi"};
const normalize=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/\b(rhp|lhp|jr|sr|ii|iii|iv)\b/g,"").replace(/[^a-z0-9]/g,"");
const slug=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[’']/g,"").replace(/\b(jr|sr|ii|iii|iv)\b/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const numeric=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?n:null},best=(q:Quote[],s:"Over"|"Under")=>q.filter(x=>x.side===s).sort((a,b)=>b.odds-a.odds)[0];
function chooseMarket(quotes:Quote[]):Market|null{const main=quotes.filter(q=>q.main),pool=main.length?main:quotes,coverage=new Map<number,Set<string>>();for(const q of pool){if(!coverage.has(q.line))coverage.set(q.line,new Set());coverage.get(q.line)!.add(`${q.book}-${q.side}`)}const line=[...coverage].sort((a,b)=>b[1].size-a[1].size||a[0]-b[0])[0]?.[0];if(line==null)return null;const at=pool.filter(q=>q.line===line),over=best(at,"Over"),under=best(at,"Under");return{line,overOdds:over?.odds??null,underOdds:under?.odds??null,overBook:over?.book??null,underBook:under?.book??null}}
function readOffers(html:string):Offer[]{for(const match of html.matchAll(/<script[^>]*class=["']island-props["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const p=JSON.parse(match[1]);if(Array.isArray(p.marketSelectorOffers))return p.marketSelectorOffers}catch{}}return[]}
async function fetchPitcher(name:string){const response=await fetch(`https://www.bettingpros.com/mlb/props/${slug(name)}/strikeouts/`,{headers:{Accept:"text/html,application/xhtml+xml","User-Agent":"Mozilla/5.0 (compatible; HallmanMLBModel/1.0)"},cache:"no-store",signal:AbortSignal.timeout(12000)});if(!response.ok)throw new Error(`BettingPros returned ${response.status}`);const offers=readOffers(await response.text());if(!offers.length)throw new Error("No structured pitcher markets were found");const quotes:Record<string,Quote[]>={};for(const offer of offers){const market=offer.market_id&&marketKeys[offer.market_id];if(!market)continue;quotes[market]??=[];for(const selection of offer.selections||[]){const side=selection.selection?.toLowerCase()==="over"?"Over":selection.selection?.toLowerCase()==="under"?"Under":null;if(!side)continue;for(const book of selection.books||[]){const bookName=allowedBooks[book.id];if(!bookName)continue;for(const line of book.lines||[]){const threshold=numeric(line.line),odds=numeric(line.cost);if(line.active===false||line.is_off===true||threshold==null||odds==null)continue;quotes[market].push({line:threshold,odds,book:bookName,side,main:line.main===true})}}}}const strikeoutMain=chooseMarket(quotes.SO||[]),alternateStrikeouts=[...new Set((quotes.SO||[]).map(q=>q.line).filter(line=>line!==strikeoutMain?.line))].sort((a,b)=>a-b).map(line=>{const quote=best((quotes.SO||[]).filter(q=>q.line===line),"Over");return{line,overOdds:quote?.odds??null,book:quote?.book??null}});return{markets:{SO:strikeoutMain,BB:chooseMarket(quotes.BB||[]),ER:chooseMarket(quotes.ER||[]),HITS:chooseMarket(quotes.HITS||[]),OUTS:chooseMarket(quotes.OUTS||[])},alternateStrikeouts} as PitcherOdds}
export async function POST(request:NextRequest){try{const body=await request.json().catch(()=>({})),games=Array.isArray(body.games)?body.games:[],upcoming=games.filter((g:any)=>!g.started&&Date.parse(g.startTime||"")>Date.now());if(!upcoming.length)return NextResponse.json({error:"There are no upcoming games to test."},{status:400});const names=[...new Set(upcoming.flatMap((g:any)=>[g.away?.pitcher,g.home?.pitcher]).filter((n:unknown):n is string=>typeof n==="string"&&n.trim()!==""&&n!=="TBD"))],byPitcher:Record<string,PitcherOdds>={},failures:{pitcher:string;error:string}[]=[];for(let i=0;i<names.length;i+=5){const slice=names.slice(i,i+5),batch=await Promise.allSettled(slice.map(async name=>({name,odds:await fetchPitcher(name)})));batch.forEach((item,index)=>{if(item.status==="fulfilled")byPitcher[normalize(item.value.name)]=item.value.odds;else failures.push({pitcher:slice[index],error:item.reason instanceof Error?item.reason.message:"Unavailable"})})}const marketCount=Object.values(byPitcher).reduce((n,p)=>n+Object.values(p.markets).filter(Boolean).length,0);if(!marketCount)return NextResponse.json({error:"BettingPros did not return any active markets for today’s upcoming starters.",failures},{status:502});return NextResponse.json({source:"BettingPros",fetchedAt:new Date().toISOString(),eventCount:upcoming.length,pitcherCount:Object.keys(byPitcher).length,marketCount,byPitcher,failures})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"BettingPros could not be tested."},{status:502})}}
