import { NextResponse } from "next/server";
export const dynamic = "force-dynamic";
const season = "2026";
const root = "https://baseballsavant.mlb.com/leaderboard";
function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[],field="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++}else quoted=!quoted}else if(c===","&&!quoted){row.push(field);field=""}else if((c==="\n"||c==="\r")&&!quoted){if(c==="\r"&&text[i+1]==="\n")i++;row.push(field);if(row.some(Boolean))rows.push(row);row=[];field=""}else field+=c}if(field||row.length){row.push(field);rows.push(row)}const headers=rows.shift()??[];return rows.map(values=>Object.fromEntries(headers.map((h,i)=>[h,values[i]??""])))}
async function csv(url:string){const r=await fetch(url,{headers:{Accept:"text/csv","User-Agent":"Hallman-MLB-Model/1.0"},cache:"no-store"});if(!r.ok)throw new Error(`Statcast request failed (${r.status}).`);return parseCsv(await r.text())}
const num=(v:unknown)=>v===""||v==null?null:Number(v);
const name=(v:string)=>{const[last,...first]=v.split(",");return`${first.join(",").trim()} ${last.trim()}`.trim()};
async function teamMap(ids:number[]){const map=new Map<number,string>();for(let i=0;i<ids.length;i+=100){const r=await fetch(`https://statsapi.mlb.com/api/v1/people?personIds=${ids.slice(i,i+100).join(",")}&hydrate=currentTeam`,{cache:"no-store"});if(!r.ok)continue;const body=await r.json() as {people?:Array<{id:number;currentTeam?:{abbreviation?:string;name?:string}}>};for(const p of body.people??[])map.set(p.id,p.currentTeam?.abbreviation??p.currentTeam?.name??"—")}return map}
export async function GET(){try{const[contact,expected,tracking,path]=await Promise.all([csv(`${root}/statcast?type=batter&year=${season}&position=&team=&min=1&sort=6&sortDir=desc&csv=true`),csv(`${root}/expected_statistics?type=batter&year=${season}&position=&team=&min=1&csv=true`),csv(`${root}/bat-tracking?year=${season}&type=batter&team=&minSwings=1&minGroup=1&sortColumn=avg_bat_speed&sortDirection=desc&csv=true`),csv(`${root}/bat-tracking/swing-path-attack-angle?gameType=Regular&minGroupSwings=1&minSwings=1&seasonEnd=${season}&seasonStart=${season}&type=batter&csv=true`)]);const exp=new Map(expected.map(r=>[Number(r.player_id),r])),trk=new Map(tracking.map(r=>[Number(r.id),r])),pth=new Map(path.map(r=>[Number(r.id),r]));void trk;const ids=[...new Set([...contact.map(r=>Number(r.player_id)),...tracking.map(r=>Number(r.id))].filter(Boolean))],teams=await teamMap(ids);const statcast=contact.map((r,i)=>{const id=Number(r.player_id),e=exp.get(id)??{};return{rank:i+1,playerId:id,name:name(r["last_name, first_name"]),team:teams.get(id)??"—",pa:num(e.pa),events:num(r.attempts),ev:num(r.avg_hit_speed),ev90:num(r.ev50),maxEv:num(r.max_hit_speed),la:num(r.avg_hit_angle),barrels:num(r.barrels),barrelPct:num(r.brl_percent)==null?null:Number(r.brl_percent)/100,hardHit:num(r.ev95plus),hardHitPct:num(r.ev95percent)==null?null:Number(r.ev95percent)/100,avg:num(e.ba),xba:num(e.est_ba),slg:num(e.slg),xslg:num(e.est_slg),woba:num(e.woba),xwoba:num(e.est_woba)}});const batTracking=tracking.map((r,i)=>{const id=Number(r.id),p=pth.get(id)??{};return{rank:i+1,playerId:id,name:name(r.name),team:teams.get(id)??"—",competitiveSwings:num(r.swings_competitive),batSpeed:num(r.avg_bat_speed),fastSwingPct:num(r.hard_swing_rate),swingLength:num(r.swing_length),squaredContactPct:num(r.squared_up_per_bat_contact),squaredSwingPct:num(r.squared_up_per_swing),blastContactPct:num(r.blast_per_bat_contact),blastSwingPct:num(r.blast_per_swing),tilt:num(p.swing_tilt),attackAngle:num(p.attack_angle),attackDirection:num(p.attack_direction),idealAttackAnglePct:num(p.ideal_attack_angle_rate)}});return NextResponse.json({season:Number(season),fetchedAt:new Date().toISOString(),source:"MLB Statcast (Baseball Savant)",fanGraphsUrl:"https://www.fangraphs.com/leaders/major-league?pos=all&type=24&qual=1",statcast,batTracking},{headers:{"Cache-Control":"public, max-age=300, stale-while-revalidate=3600"}})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Hitter Statcast data is unavailable."},{status:502})}}
