"use client";
import { useMemo, useState } from "react";
type Point={value:number;probability:number}; type Result={model:number;book:number;edge:number;fair:number|null;units:number};
const base:Point[]=[.2139,.2091,.1715,.1257,.1038,.0593,.0491,.0275,.0175,.011,.0052,.003,.0017,.0004,.0002].map((probability,value)=>({value,probability}));
const implied=(o:number)=>o>0?100/(o+100):o<0?-o/(-o+100):.5, american=(p:number)=>p<=0||p>=1?null:p>.5?-100*p/(1-p):100*(1-p)/p;
const pct=(v:number)=>`${(v*100).toFixed(2)}%`, odds=(v:number|null)=>v==null?"—":`${v>0?"+":""}${Math.round(v)}`;
function tilt(target:number){let lo=-10,hi=10;const mean=(t:number)=>{const w=base.map(p=>p.probability*Math.exp(t*p.value)),z=w.reduce((a,b)=>a+b,0);return w.reduce((s,x,i)=>s+x*base[i].value,0)/z};for(let i=0;i<100;i++){const m=(lo+hi)/2;if(mean(m)<target)lo=m;else hi=m}const t=(lo+hi)/2,w=base.map(p=>p.probability*Math.exp(t*p.value)),z=w.reduce((a,b)=>a+b,0);return base.map((p,i)=>({...p,probability:w[i]/z}))}
function outcome(model:number,bookOdds:string,multiplier=model):Result{const book=implied(Number(bookOdds)),edge=model-book;return{model,book,edge,fair:american(model),units:edge>.0499?edge*8*(multiplier*.8)*25:0}}
function Side({label,r}:{label:string;r:Result}){return <div className={r.edge>0?"positive":""}><span>{label}</span><strong>{pct(r.model)}</strong><small>Fair {odds(r.fair)} · Book {pct(r.book)}</small><b>Edge {pct(r.edge)}</b><em>{r.units?`${r.units.toFixed(2)} units`:"No play"}</em></div>}
function Market({title,leftLabel,rightLabel,left,right,children}:{title:string;leftLabel:string;rightLabel:string;left:Result;right:Result;children:React.ReactNode}){return <article className="prop-card f5-market"><div className="prop-card-title"><div><span>F5</span><h3>{title}</h3></div></div>{children}<div className="prop-sides"><Side label={leftLabel} r={left}/><Side label={rightLabel} r={right}/></div></article>}
export default function F5OddsPanel({away,home,awayRuns,homeRuns}:{away:string;home:string;awayRuns:number;homeRuns:number}){
 const[inputs,setInputs]=useState({mlAway:"155",mlHome:"-150",rlAway:"128",rlHome:"110",totalLine:"4.5",totalOver:"-140",totalUnder:"-115",awayTtLine:"1.5",awayTtOver:"-105",awayTtUnder:"100",homeTtLine:"1.5",homeTtOver:"-125",homeTtUnder:"-105"}),set=(key:keyof typeof inputs,value:string)=>setInputs(s=>({...s,[key]:value}));
 const r=useMemo(()=>{const a=tilt(awayRuns),h=tilt(homeRuns);let aw=0,hw=0,tie=0,totalOver=0,aOver=0,hOver=0;for(const x of a){if(x.value>Number(inputs.awayTtLine))aOver+=x.probability;for(const y of h){const p=x.probability*y.probability;if(x.value>y.value)aw+=p;else if(y.value>x.value)hw+=p;else tie+=p;if(x.value+y.value>Number(inputs.totalLine))totalOver+=p}}for(const y of h)if(y.value>Number(inputs.homeTtLine))hOver+=y.probability;const aMl=aw+tie/2,hMl=hw+tie/2;return{tie,mlA:outcome(aMl,inputs.mlAway),mlH:outcome(hMl,inputs.mlHome),rlA:outcome(aw,inputs.rlAway,aMl),rlH:outcome(hw,inputs.rlHome,hMl),totO:outcome(totalOver,inputs.totalOver),totU:outcome(1-totalOver,inputs.totalUnder),attO:outcome(aOver,inputs.awayTtOver),attU:outcome(1-aOver,inputs.awayTtUnder),httO:outcome(hOver,inputs.homeTtOver),httU:outcome(1-hOver,inputs.homeTtUnder)}},[awayRuns,homeRuns,inputs]);
 const fields=(items:[string,keyof typeof inputs][])=> <div className="prop-input-row">{items.map(([label,key])=><label key={key}>{label}<input inputMode="decimal" value={inputs[key]} onChange={e=>set(key,e.target.value)}/></label>)}</div>;
 return <section className="props-panel f5-panel"><div className="props-heading"><div><span>First five innings</span><h2>F5 odds model</h2><p>Team-run distributions · exact exponential tilt · sportsbook inputs are manual</p></div><strong>Tie {pct(r.tie)}</strong></div><div className="f5-score-kpis"><div><span>{away}</span><strong>{awayRuns.toFixed(2)}</strong><small>Projected F5 runs</small></div><div><span>{home}</span><strong>{homeRuns.toFixed(2)}</strong><small>Projected F5 runs</small></div><div><span>Total</span><strong>{(awayRuns+homeRuns).toFixed(2)}</strong><small>Home diff {(homeRuns-awayRuns).toFixed(2)}</small></div></div><div className="prop-grid f5-grid">
 <Market title="Moneyline" leftLabel={away} rightLabel={home} left={r.mlA} right={r.mlH}>{fields([[`${away} odds`,"mlAway"],[`${home} odds`,"mlHome"]])}</Market>
 <Market title="-0.5 run line" leftLabel={`${away} -0.5`} rightLabel={`${home} -0.5`} left={r.rlA} right={r.rlH}>{fields([[`${away} odds`,"rlAway"],[`${home} odds`,"rlHome"]])}</Market>
 <Market title="Game total" leftLabel="Over" rightLabel="Under" left={r.totO} right={r.totU}>{fields([["Line","totalLine"],["Over odds","totalOver"],["Under odds","totalUnder"]])}</Market>
 <Market title={`${away} team total`} leftLabel="Over" rightLabel="Under" left={r.attO} right={r.attU}>{fields([["Line","awayTtLine"],["Over odds","awayTtOver"],["Under odds","awayTtUnder"]])}</Market>
 <Market title={`${home} team total`} leftLabel="Over" rightLabel="Under" left={r.httO} right={r.httU}>{fields([["Line","homeTtLine"],["Over odds","homeTtOver"],["Under odds","homeTtUnder"]])}</Market>
 </div></section>
}
