"use client";
import { useEffect, useMemo, useState } from "react";
type Payload={season:number;fetchedAt:string;source:string;fanGraphsUrl:string;statcast:Record<string,unknown>[];batTracking:Record<string,unknown>[]};
const left=[["rank","#"],["name","Name"],["team","Team"],["pa","PA"],["events","Events"],["ev","EV"],["ev90","EV90"],["maxEv","maxEV"],["la","LA"],["barrels","Barrels"],["barrelPct","Barrel%"],["hardHit","HardHit"],["hardHitPct","HardHit%"],["avg","AVG"],["xba","xBA"],["slg","SLG"],["xslg","xSLG"],["woba","wOBA"],["xwoba","xwOBA"]] as const;
const right=[["rank","#"],["name","Name"],["team","Team"],["competitiveSwings","CompSw"],["batSpeed","BatSpd"],["fastSwingPct","FastSw%"],["swingLength","SwgLng"],["squaredContactPct","SqUpCon%"],["squaredSwingPct","SqUpSw%"],["blastContactPct","BlastCon%"],["blastSwingPct","BlastSw%"],["tilt","Tilt"],["attackAngle","AtkAng"],["attackDirection","AtkDir"],["idealAttackAnglePct","IdealAtkAng%"]] as const;
const percentages=new Set(["barrelPct","hardHitPct","fastSwingPct","squaredContactPct","squaredSwingPct","blastContactPct","blastSwingPct","idealAttackAnglePct"]);
function format(value:unknown,key:string){if(value==null||value==="")return"—";if(typeof value!=="number")return String(value);if(percentages.has(key))return`${(value*100).toFixed(1)}%`;if(["avg","xba","slg","xslg","woba","xwoba"].includes(key))return value.toFixed(3).replace(/^0/,"");if(["ev","ev90","maxEv","la","batSpeed","swingLength","tilt","attackAngle","attackDirection"].includes(key))return value.toFixed(1);return value.toLocaleString()}
function Table({title,rows,columns}:{title:string;rows:Record<string,unknown>[];columns:readonly(readonly[string,string])[]}){return<section className="stat-table-card"><div className="table-title"><div><p>Workbook table</p><h2>{title}</h2></div><span>{rows.length} hitters</span></div><div className="table-scroll"><table><thead><tr>{columns.map(([key,label])=><th key={key}>{label}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.playerId??i)}>{columns.map(([key])=><td className={key==="name"?"player-name":""} key={key}>{format(row[key],key)}</td>)}</tr>)}</tbody></table></div></section>}
export default function HitterStatcast(){const[data,setData]=useState<Payload|null>(null),[error,setError]=useState(""),[query,setQuery]=useState("");useEffect(()=>{fetch("/api/hitter-statcast",{cache:"no-store"}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error||"Hitter data could not be loaded.");setData(body)}).catch(e=>setError(e instanceof Error?e.message:"Hitter data could not be loaded."))},[]);const filtered=useMemo(()=>{if(!data)return null;const q=query.trim().toLowerCase();if(!q)return data;return{...data,statcast:data.statcast.filter(r=>`${r.name} ${r.team}`.toLowerCase().includes(q)),batTracking:data.batTracking.filter(r=>`${r.name} ${r.team}`.toLowerCase().includes(q))}},[data,query]);return<><section className="stats-hero"><div><p className="eyebrow">HIT STATCAST</p><h1>Hitter quality,<br/><em>ready every morning.</em></h1><p className="hero-copy">These two tables match the Statcast and Statcast – Bat Tracking sections in your Excel model.</p></div><div className="stat-controls"><label htmlFor="player-search">Find a hitter or team</label><input id="player-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Aaron Judge or NYY"/><div><span>Season</span><strong>{data?.season||"—"}</strong></div><div><span>Scheduled update</span><strong>9:00 AM ET daily</strong></div></div></section>{error&&<div className="error"><strong>Couldn’t load hitter data.</strong><span>{error}</span></div>}{!data&&!error?<div className="loading-card"/>:filtered&&<div className="stat-tables"><Table title="Statcast" rows={filtered.statcast} columns={left}/><Table title="Statcast – Bat Tracking" rows={filtered.batTracking} columns={right}/></div>}{data&&<footer>Last updated {new Date(data.fetchedAt).toLocaleString("en-US",{timeZone:"America/New_York"})} ET · Source: {data.source} · <a href={data.fanGraphsUrl} target="_blank" rel="noreferrer">FanGraphs reference</a></footer>}</>}
