"use client";
import { useEffect, useMemo, useState } from "react";
import fanGraphsBatTracking from "../data/fangraphs-bat-tracking-2026.json";
import savantPitches from "../data/baseball-savant-hitter-pitches-bb-2026.json";
type Payload={season:number;fetchedAt:string;source:string;fanGraphsUrl:string;statcast:Record<string,unknown>[];batTracking:Record<string,unknown>[];battedBall:Record<string,unknown>[];battedBallUrl:string};
const left=[["rank","#"],["name","Name"],["team","Team"],["pa","PA"],["events","Events"],["ev","EV"],["ev90","EV90"],["maxEv","maxEV"],["la","LA"],["barrels","Barrels"],["barrelPct","Barrel%"],["hardHit","HardHit"],["hardHitPct","HardHit%"],["avg","AVG"],["xba","xBA"],["slg","SLG"],["xslg","xSLG"],["woba","wOBA"],["xwoba","xwOBA"]] as const;
const right=[["rank","#"],["name","Name"],["team","Team"],["competitiveSwings","CompSw"],["batSpeed","BatSpd"],["fastSwingPct","FastSw%"],["swingLength","SwgLng"],["squaredContactPct","SqUpCon%"],["squaredSwingPct","SqUpSw%"],["blastContactPct","BlastCon%"],["blastSwingPct","BlastSw%"],["tilt","Tilt"],["attackAngle","AtkAng"],["attackDirection","AtkDir"],["idealAttackAnglePct","IdealAtkAng%"]] as const;
const battedBallColumns=[["rank","#"],["name","Name"],["team","Team"],["gbPct","GB%"],["fbPct","FB%"],["hardHitPct","Hard%"],["pullPct","Pull%"]] as const;
const savantColumns=[["rank","#"],["name","Player"],["pa","PA"],["pitches","Total Pitches Seen"],["bbPctSavant","BB%"]] as const;
const percentages=new Set(["barrelPct","hardHitPct","fastSwingPct","squaredContactPct","squaredSwingPct","blastContactPct","blastSwingPct","idealAttackAnglePct","gbPct","fbPct","pullPct"]);
function format(value:unknown,key:string){if(value==null||value==="")return"—";if(typeof value!=="number")return String(value);if(key==="bbPctSavant")return`${value.toFixed(1)}%`;if(percentages.has(key))return`${(value*100).toFixed(1)}%`;if(["avg","xba","slg","xslg","woba","xwoba"].includes(key))return value.toFixed(3).replace(/^0/,"");if(["ev","ev90","maxEv","la","batSpeed","swingLength","tilt","attackAngle","attackDirection"].includes(key))return value.toFixed(1);return value.toLocaleString()}
function Table({title,rows,columns}:{title:string;rows:Record<string,unknown>[];columns:readonly(readonly[string,string])[]}){const displayedRows:Record<string,unknown>[]=title.includes("Bat Tracking")?fanGraphsBatTracking.rows:rows;return<section className="stat-table-card"><div className="table-title"><div><p>Model table</p><h2>{title}</h2></div><span>{displayedRows.length} hitters</span></div><div className="table-scroll"><table><thead><tr>{columns.map(([key,label])=><th key={key}>{label}</th>)}</tr></thead><tbody>{displayedRows.map((row,i)=><tr key={String(row.name??i)}>{columns.map(([key])=><td className={key==="name"?"player-name":""} key={key}>{format(row[key],key)}</td>)}</tr>)}</tbody></table></div></section>}
export default function HitterStatcast(){const[data,setData]=useState<Payload|null>(null),[error,setError]=useState(""),[query,setQuery]=useState("");useEffect(()=>{Promise.all([fetch("/api/hitter-statcast",{cache:"no-store"}),fetch("/api/hitter-batted-ball",{cache:"no-store"})]).then(async([stats,batted])=>{const statsBody=await stats.json(),battedBody=await batted.json();if(!stats.ok)throw new Error(statsBody.error||"Hitter data could not be loaded.");if(!batted.ok)throw new Error(battedBody.error||"Batted-ball data could not be loaded.");setData({...statsBody,battedBall:battedBody.rows,battedBallUrl:battedBody.fanGraphsUrl})}).catch(e=>setError(e instanceof Error?e.message:"Hitter data could not be loaded."))},[]);const filtered=useMemo(()=>{if(!data)return null;const q=query.trim().toLowerCase();if(!q)return data;const match=(r:Record<string,unknown>)=>`${r.name} ${r.team}`.toLowerCase().includes(q);return{...data,statcast:data.statcast.filter(match),batTracking:data.batTracking.filter(match),battedBall:data.battedBall.filter(match)}},[data,query]);const filteredSavant=useMemo(()=>{const q=query.trim().toLowerCase();return savantPitches.rows.map(r=>({...r,name:r.player,bbPctSavant:r.bbPct})).filter(r=>!q||r.name.toLowerCase().includes(q))},[query]);return<><section className="stats-hero"><div><p className="eyebrow">HIT STATCAST</p><h1>Hitter quality,<br/><em>ready every morning.</em></h1><p className="hero-copy">These tables match the Statcast, batted-ball, Bat Tracking, and Baseball Savant sections used by your model.</p></div><div className="stat-controls"><label htmlFor="player-search">Find a hitter or team</label><input id="player-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Aaron Judge or NYY"/><div><span>Season</span><strong>{data?.season||"—"}</strong></div><div><span>Scheduled update</span><strong>9:00 AM ET daily</strong></div></div></section>{error&&<div className="error"><strong>Couldn’t load hitter data.</strong><span>{error}</span></div>}{!data&&!error?<div className="loading-card"/>:filtered&&<div className="stat-tables"><Table title="Statcast" rows={filtered.statcast} columns={left}/><Table title="Batted Ball" rows={filtered.battedBall} columns={battedBallColumns}/><Table title="Statcast – Bat Tracking" rows={filtered.batTracking} columns={right}/><Table title="Baseball Savant — Pitches & BB%" rows={filteredSavant} columns={savantColumns}/></div>}{data&&<footer>Last updated {new Date(data.fetchedAt).toLocaleString("en-US",{timeZone:"America/New_York"})} ET · Source: {data.source} · <a href={data.fanGraphsUrl} target="_blank" rel="noreferrer">FanGraphs Statcast</a> · <a href={data.battedBallUrl} target="_blank" rel="noreferrer">FanGraphs batted ball</a> · <a href={savantPitches.sourceUrl} target="_blank" rel="noreferrer">Baseball Savant</a></footer>}</>}
