"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import PitcherMatchupModel from "./PitcherMatchupModel";
import TeamProjectionPanel from "./TeamProjectionPanel";
import F5OddsPanel from "./F5OddsPanel";
import savant from "../data/baseball-savant-hitter-pitches-bb-2026.json";
import battedBall from "../data/fangraphs-batted-ball-2026.json";
import batTracking from "../data/fangraphs-bat-tracking-2026.json";
import zips from "../data/fangraphs-zips-update-hitting-2026.json";
import hitterVsR from "../data/fangraphs-steamer-ros-hitting-vs-rhp-2026.json";
import hitterVsL from "../data/fangraphs-steamer-ros-hitting-vs-lhp-2026.json";
import pitcherVsR from "../data/fangraphs-steamer-ros-pitching-vs-rhb-2026.json";
import pitcherVsL from "../data/fangraphs-steamer-ros-pitching-vs-lhb-2026.json";
import pitcherStandard from "../data/fangraphs-pitcher-standard-2026.json";
import { workbookPaWeights } from "./modelWeights";

type Player={order:number;playerId:number;name:string;bats:string;position:string};
type Team={name:string;abbreviation:string;pitcher:string;pitcherId:number|null;throws:string;lineup:Player[];lineupStatus:string};
type Game={gamePk:number;gameTime:string;venue:string;status:string;away:Team;home:Team};
type Statcast={playerId:number;name:string;ev:number|null;la:number|null;barrelPct:number|null;hardHitPct:number|null};
const normalize=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/\b(rhp|lhp|jr|sr|ii|iii|iv)\b/g,"").replace(/[^a-z0-9]/g,"");
const effectiveHand=(bats:string,throws:string)=>bats==="S"?(throws==="R"?"L":"R"):bats;
const names=(value:string)=>{const clean=value.replace(/\b(RHP|LHP)\b/gi,"").trim(),parts=clean.split(",").map(x=>x.trim());return new Set([normalize(clean),parts.length===2?normalize(`${parts[1]} ${parts[0]}`):normalize(clean)])};
const byName=<T extends {name?:string;player?:string}>(rows:T[],name:string)=>{const set=names(name);return rows.find(row=>set.has(normalize(row.name||row.player||"")))};
const fgRow=(rows:{playerId:number|null;values:string[]}[],id:number,name:string)=>rows.find(row=>row.playerId===id)||rows.find(row=>names(row.values[1]||"").has(normalize(name)));
const num=(v:unknown)=>{const x=Number(String(v??"").replace(/[%,$]/g,""));return Number.isFinite(x)?x:null};
const ratio=(v:unknown)=>{const raw=String(v??""),x=num(v);return x==null?null:raw.includes("%")?x/100:x};
const fg=(headers:string[],row:{values:string[]}|undefined,label:string,asRate=false)=>row?(asRate?ratio(row.values[headers.indexOf(label)]):num(row.values[headers.indexOf(label)])):null;
const pct=(v:number|null,d=2)=>v==null?"—":`${(v*100).toFixed(d)}%`, dec=(v:number|null,d=2)=>v==null?"—":v.toFixed(d), whole=(v:number|null)=>v==null?"—":Math.round(v).toLocaleString();
const weighted=(a:number|null,aw:number|null,b:number|null,bw:number|null)=>a!=null&&aw!=null&&b!=null&&bw!=null&&aw+bw?((a*aw)+(b*bw))/(aw+bw):a??b;

const columns=["#","NAME","HAND","PITCHES","PA","STRIKES","Called K","Swing K","Foul K","PIT/PA","BB%","EV","LA","BARREL%","BAT SPEED","ATT ANG","GB%","FB%","HH%","PULL%","xHR/BBE","xBABIP","ROS PA","ROS K%","ROS BB%","ROS HR/PA","ROS BABIP","PITCH ROS K%","PITCH ROS BB%","COMB K%","COMB PA","PA %","ROS PA%","COMB BB%","ROS HR/BBE","PITCH ROS HR/BBE","COMB HR","BABIP","R PA","L PA","ROS PA TOTAL","R K%","L K%","K% DIFF","R BB%","L BB%","BB% DIFF","R HR/PA","L HR/PA","HR% DIFF","R BABIP","L BABIP","BABIP DIFF","ZIPS PA","ZIPS PA V R","ZIPS PA V L"];

function makeRow(player:Player,opponent:Team,statcast:Statcast[]){
  const batHand=effectiveHand(player.bats,opponent.throws),sv=savant.rows.find(r=>r.playerId===player.playerId)||byName(savant.rows,player.name),bb=byName(battedBall.rows,player.name),bt=byName(batTracking.rows,player.name),sc=statcast.find(r=>r.playerId===player.playerId)||byName(statcast,player.name),r=fgRow(hitterVsR.rows,player.playerId,player.name),l=fgRow(hitterVsL.rows,player.playerId,player.name),zp=fgRow(zips.rows,player.playerId,player.name);
  const pitchTable=batHand==="L"?pitcherVsL:pitcherVsR,pitchRow=fgRow(pitchTable.rows,opponent.pitcherId||0,opponent.pitcher);
  const pitches=sv?.pitches??null,pa=sv?.pa??null,strikes=sv?.totalStrikes??null,called=strikes&&sv?sv.calledStrikes/strikes:null,swing=strikes&&sv?sv.totalSwingingStrikes/strikes:null,foul=strikes&&sv?sv.foulStrikes/strikes:null,pitPa=pitches&&pa?pitches/pa:null,bbPct=sv?.bbPct==null?null:sv.bbPct/100;
  const ev=sc?.ev??null,la=sc?.la??null,barrel=sc?.barrelPct??null,batSpeed=bt?.batSpeed??null,attack=bt?.attackAngle??null,gb=bb?.gbPct??null,fb=bb?.fbPct??null,hh=bb?.hardHitPct??sc?.hardHitPct??null,pull=bb?.pullPct??null;
  const xHr=[ev,la,barrel,batSpeed,attack].some(v=>v==null)?null:-.225747214+.000895322*ev!+.000955001*la!+.173182398*barrel!+.002263657*batSpeed!+.000825565*attack!;
  const xBabip=[gb,fb,barrel,hh,pull].some(v=>v==null)?null:.740027311-.47190989*gb!-.657861189*fb!+.205288968*barrel!+.058427751*hh!-.096578548*pull!;
  const rPa=fg(hitterVsR.headers,r,"PA"),lPa=fg(hitterVsL.headers,l,"PA"),rosPa=(rPa??0)+(lPa??0)||null,rK=fg(hitterVsR.headers,r,"K%",true),lK=fg(hitterVsL.headers,l,"K%",true),rBB=fg(hitterVsR.headers,r,"BB%",true),lBB=fg(hitterVsL.headers,l,"BB%",true),rHR=rPa?fg(hitterVsR.headers,r,"HR")!/rPa:null,lHR=lPa?fg(hitterVsL.headers,l,"HR")!/lPa:null,rBabip=fg(hitterVsR.headers,r,"BABIP"),lBabip=fg(hitterVsL.headers,l,"BABIP");
  const rosK=weighted(rK,rPa,lK,lPa),rosBB=weighted(rBB,rPa,lBB,lPa),rosHR=weighted(rHR,rPa,lHR,lPa),rosBabip=weighted(rBabip,rPa,lBabip,lPa),rosHrBbe=rosHR!=null&&rosK!=null&&rosBB!=null?rosHR/(1-rosK-rosBB-.01):null;
  const pitchK=fg(pitchTable.headers,pitchRow,"K%",true),pitchBB=fg(pitchTable.headers,pitchRow,"BB%",true),pTbf=fg(pitchTable.headers,pitchRow,"TBF"),pHr=fg(pitchTable.headers,pitchRow,"HR"),pitchHrBbe=pHr!=null&&pTbf&&pitchK!=null&&pitchBB!=null?(pHr/pTbf)/(1-pitchK-pitchBB-.01):null;
  const pitchStandardRow=pitcherStandard.rows.find(row=>names(row[1]||"").has(normalize(opponent.pitcher))),pitchCurrentTbf=pitchStandardRow?num(pitchStandardRow[pitcherStandard.headers.indexOf("TBF")]):null,pitchRosTbf=(fg(pitcherVsR.headers,fgRow(pitcherVsR.rows,opponent.pitcherId||0,opponent.pitcher),"TBF")??0)+(fg(pitcherVsL.headers,fgRow(pitcherVsL.rows,opponent.pitcherId||0,opponent.pitcher),"TBF")??0),zipsPaForWeight=fg(zips.headers,zp,"PA"),weights=workbookPaWeights(pa??0,zipsPaForWeight??0,pitchCurrentTbf??0,pitchRosTbf),paPct=weights.paPct,rosPaPct=weights.rosPaPct;
  const combK=rosK!=null&&pitchK!=null?-.219896067+1.045705467*rosK+.948551136*pitchK:null,combBB=rosBB!=null&&pitchBB!=null?-.076346102+1.028505877*pitchBB+.883781327*rosBB:null,combHr=rosHrBbe!=null&&pitchHrBbe!=null?-.03260003+.62347016*pitchHrBbe+.676284139*rosHrBbe:null,combPa=(pa??0)+(rosPa??0)||null,babip=weighted(xBabip,paPct,rosBabip,rosPaPct);
  const zipsPa=fg(zips.headers,zp,"PA"),zR=zipsPa!=null&&rosPa&&rPa!=null?zipsPa*rPa/rosPa:null,zL=zipsPa!=null&&rosPa&&lPa!=null?zipsPa*lPa/rosPa:null;
  return [String(player.order),player.name,player.bats==="S"?`S→${batHand}`:(batHand||"—"),whole(pitches),whole(pa),whole(strikes),pct(called),pct(swing),pct(foul),dec(pitPa),pct(bbPct,1),dec(ev,1),dec(la,1),pct(barrel,1),dec(batSpeed,1),dec(attack,1),pct(gb,1),pct(fb,1),pct(hh,1),pct(pull,1),pct(xHr),dec(xBabip,3),whole(rosPa),pct(rosK),pct(rosBB),pct(rosHR),dec(rosBabip,3),pct(pitchK),pct(pitchBB),pct(combK),whole(combPa),pct(paPct),pct(rosPaPct),pct(combBB),pct(rosHrBbe),pct(pitchHrBbe),pct(combHr),dec(babip,3),whole(rPa),whole(lPa),whole(rosPa),pct(rK),pct(lK),pct(rK!=null&&lK!=null?rK-lK:null),pct(rBB),pct(lBB),pct(rBB!=null&&lBB!=null?rBB-lBB:null),pct(rHR),pct(lHR),pct(rHR!=null&&lHR!=null?rHR-lHR:null),dec(rBabip,3),dec(lBabip,3),dec(rBabip!=null&&lBabip!=null?rBabip-lBabip:null,3),whole(zipsPa),whole(zR),whole(zL)];
}

export default function MatchupLineupScreen({game,onBack}:{game:Game;onBack:()=>void}){const[side,setSide]=useState<"away"|"home">("away"),[statcast,setStatcast]=useState<Statcast[]>([]),[f5,setF5]=useState({away:2.5,home:2.5});useEffect(()=>{fetch("/api/hitter-statcast",{cache:"no-store"}).then(r=>r.json()).then(body=>setStatcast(body.statcast||[])).catch(()=>setStatcast([]))},[]);const team=game[side],opponent=game[side==="away"?"home":"away"],rows=useMemo(()=>team.lineup.map(player=>makeRow(player,opponent,statcast)),[team,opponent,statcast]),onAway=useCallback((p:{f5Runs:number})=>setF5(s=>s.away===p.f5Runs?s:{...s,away:p.f5Runs}),[]),onHome=useCallback((p:{f5Runs:number})=>setF5(s=>s.home===p.f5Runs?s:{...s,home:p.f5Runs}),[]);return <section className="matchup-screen"><div className="matchup-screen-head"><button onClick={onBack}>← Back to slate</button><div><span>{game.status} · {game.gameTime}</span><h1>{game.away.abbreviation} <em>at</em> {game.home.abbreviation}</h1><p>{game.venue}</p></div></div><div className="lineup-tabs" role="tablist"><button className={side==="away"?"active":""} onClick={()=>setSide("away")}>Away Lineup · {game.away.abbreviation}</button><button className={side==="home"?"active":""} onClick={()=>setSide("home")}>Home Lineup · {game.home.abbreviation}</button></div><div className="lineup-context"><div><span>Batting team</span><strong>{team.name}</strong><small>{team.lineupStatus}</small></div><div><span>Opposing pitcher</span><strong>{opponent.pitcher}</strong><small>{opponent.throws}HP · {opponent.abbreviation}</small></div></div><div hidden={side!=="away"}><TeamProjectionPanel team={game.away} opponent={game.home} side="away" onProjection={onAway}/></div><div hidden={side!=="home"}><TeamProjectionPanel team={game.home} opponent={game.away} side="home" onProjection={onHome}/></div><F5OddsPanel away={game.away.abbreviation} home={game.home.abbreviation} awayRuns={f5.away} homeRuns={f5.home}/><div className="lineup-model-table"><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={team.lineup[i]?.playerId||i}>{row.map((value,j)=><td className={j===1?"player-name":""} key={j}>{value}</td>)}</tr>)}</tbody></table></div><PitcherMatchupModel away={game.away} home={game.home}/></section>}
