"use client";
import { useEffect, useMemo, useState } from "react";
import savant from "../data/baseball-savant-hitter-pitches-bb-2026.json";
import zips from "../data/fangraphs-zips-update-hitting-2026.json";
import hitterVsR from "../data/fangraphs-steamer-ros-hitting-vs-rhp-2026.json";
import hitterVsL from "../data/fangraphs-steamer-ros-hitting-vs-lhp-2026.json";
import pitcherVsR from "../data/fangraphs-steamer-ros-pitching-vs-rhb-2026.json";
import pitcherVsL from "../data/fangraphs-steamer-ros-pitching-vs-lhb-2026.json";
import parkFactors from "../data/mlb-park-factors.json";

type Player={order:number;playerId:number;name:string;bats:string;position:string};
type Team={name:string;abbreviation:string;pitcher:string;pitcherId:number|null;throws:string;lineup:Player[];lineupStatus:string};
type Statcast={playerId:number;name:string;ev:number|null;la:number|null;barrelPct:number|null;hardHitPct:number|null};
const normalize=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/\b(rhp|lhp|jr|sr|ii|iii|iv)\b/g,"").replace(/[^a-z0-9]/g,"");
const names=(v:string)=>{const clean=v.replace(/\b(RHP|LHP)\b/gi,"").trim(),p=clean.split(",").map(x=>x.trim());return new Set([normalize(clean),p.length===2?normalize(`${p[1]} ${p[0]}`):normalize(clean)])};
const findFg=(rows:{playerId:number|null;values:string[]}[],id:number,name:string)=>rows.find(r=>r.playerId===id)||rows.find(r=>names(r.values[1]||"").has(normalize(name)));
const n=(v:unknown)=>{const x=Number(String(v??"").replace(/[%,$]/g,""));return Number.isFinite(x)?x:null};
const rate=(v:unknown)=>{const x=n(v);return x==null?null:String(v).includes("%")?x/100:x};
const cell=(table:{headers:string[]},row:{values:string[]}|undefined,label:string,asRate=false)=>row?(asRate?rate(row.values[table.headers.indexOf(label)]):n(row.values[table.headers.indexOf(label)])):null;
const fmtPct=(v:number|null)=>v==null?"—":`${(v*100).toFixed(2)}%`;
const aliases:Record<string,string>={OAK:"ATH",AZ:"ARI",CWS:"CHW",KC:"KCR",SF:"SFG",SD:"SDP",TB:"TBR",WSH:"WSN"};
const adjustments={away:{k:1.066,bb:.947,hr:.977,babip:.986},home:{k:.938,bb:1.056,hr:1.024,babip:1.014}};
const factors=parkFactors.rows as {team:string;player:string;park:string;hr:number;babip:number}[];

function parkFor(player:Player,team:Team){const exact=factors.find(r=>normalize(r.player)===normalize(player.name));if(exact)return {...exact,fallback:false};const teamCode=aliases[team.abbreviation]||team.abbreviation,sameHand=new Set(team.lineup.filter(p=>p.bats===player.bats).map(p=>normalize(p.name))),matched=factors.filter(r=>r.team===teamCode&&sameHand.has(normalize(r.player))),pool=matched.length?matched:factors.filter(r=>r.team===teamCode);return pool.length?{team:teamCode,player:player.name,park:pool[0].park,hr:pool.reduce((s,r)=>s+r.hr,0)/pool.length,babip:pool.reduce((s,r)=>s+r.babip,0)/pool.length,fallback:true}:{team:teamCode,player:player.name,park:"Neutral",hr:1,babip:1,fallback:true}}

export default function TeamProjectionPanel({team,opponent,side}:{team:Team;opponent:Team;side:"away"|"home"}){
 const[vegasOuts,setVegasOuts]=useState("17.5"),[projectedPitches,setProjectedPitches]=useState("100"),[statcast,setStatcast]=useState<Statcast[]>([]);
 useEffect(()=>{fetch("/api/hitter-statcast",{cache:"no-store"}).then(r=>r.json()).then(b=>setStatcast(b.statcast||[])).catch(()=>setStatcast([]))},[]);
 const rows=useMemo(()=>{const adj=adjustments[side],pitches=Number(projectedPitches)||100;return team.lineup.map((player,index)=>{const sv=savant.rows.find(r=>r.playerId===player.playerId),currentPa=sv?.pa??0,r=findFg(hitterVsR.rows,player.playerId,player.name),l=findFg(hitterVsL.rows,player.playerId,player.name),rPa=cell(hitterVsR,r,"PA")??0,lPa=cell(hitterVsL,l,"PA")??0,rosPa=rPa+lPa,curShare=currentPa+rosPa?currentPa/(currentPa+rosPa):.5,rosShare=1-curShare;
  const rosK=rosPa?((cell(hitterVsR,r,"K%",true)??0)*rPa+(cell(hitterVsL,l,"K%",true)??0)*lPa)/rosPa:null,rosBB=rosPa?((cell(hitterVsR,r,"BB%",true)??0)*rPa+(cell(hitterVsL,l,"BB%",true)??0)*lPa)/rosPa:null,rHr=rPa?(cell(hitterVsR,r,"HR")??0)/rPa:0,lHr=lPa?(cell(hitterVsL,l,"HR")??0)/lPa:0,rosHrPa=rosPa?(rHr*rPa+lHr*lPa)/rosPa:null,rosBabip=rosPa?((cell(hitterVsR,r,"BABIP")??0)*rPa+(cell(hitterVsL,l,"BABIP")??0)*lPa)/rosPa:null;
  const pitchTable=player.bats==="L"?pitcherVsL:pitcherVsR,pitch=findFg(pitchTable.rows,opponent.pitcherId||0,opponent.pitcher),pitchK=cell(pitchTable,pitch,"K%",true),pitchBB=cell(pitchTable,pitch,"BB%",true),batK=sv?.pa?sv.totalSwingingStrikes/Math.max(1,sv.totalStrikes):null,batBB=sv?.bbPct==null?null:sv.bbPct/100,currentK=batK!=null&&pitchK!=null?-.219896067+1.045705467*batK+.948551136*pitchK:null,currentBB=batBB!=null&&pitchBB!=null?-.076346102+1.028505877*pitchBB+.883781327*batBB:null;
  const zp=findFg(zips.rows,player.playerId,player.name),zipsBabip=cell(zips,zp,"BABIP"),sc=statcast.find(s=>s.playerId===player.playerId),currentHr=sc?.barrelPct==null?null:Math.max(.004,sc.barrelPct*.22),currentBabip=zipsBabip??rosBabip,pf=parkFor(player,team),blend=(a:number|null,b:number|null)=>a!=null&&b!=null?a*curShare+b*rosShare:a??b;
  const lineupPitPa=team.lineup.map(p=>{const x=savant.rows.find(s=>s.playerId===p.playerId);return x?.pa?x.pitches/x.pa:null}).filter((v):v is number=>v!=null),avgPitPa=lineupPitPa.length?lineupPitPa.reduce((a,b)=>a+b,0)/lineupPitPa.length:3.9,totalPa=pitches/avgPitPa,base=Math.floor(totalPa/9),extra=Math.max(0,Math.min(9,Math.round(totalPa-base*9)));
  return {player,pf,pa:base+(index<extra?1:0),k:Math.max(.03,blend(currentK,rosK)??.22)*adj.k,bb:Math.max(.01,blend(currentBB,rosBB)??.08)*adj.bb,hr:Math.max(.004,blend(currentHr,rosHrPa)??.03)*pf.hr*adj.hr,babip:(blend(currentBabip,rosBabip)??.290)*pf.babip*adj.babip}})},[team,opponent,side,projectedPitches,statcast]);
 const sum=(key:"k"|"bb"|"hr")=>rows.reduce((s,r)=>s+r[key]*r.pa,0),totalPa=rows.reduce((s,r)=>s+r.pa,0),avgBabip=rows.reduce((s,r)=>s+r.babip*r.pa,0)/Math.max(1,totalPa);
 return <section className="projection-card"><div className="projection-heading"><div><span>{side} projection</span><h2>{team.abbreviation} hitters vs {opponent.pitcher}</h2><p>{side==="away"?"Home pitcher boost":"Away pitcher adjustment"} · park factors fall back to the same-hand team average</p></div><div className="projection-inputs"><label>Vegas Outs<input value={vegasOuts} inputMode="decimal" onChange={e=>setVegasOuts(e.target.value)}/></label><label>Projected Pitches<input value={projectedPitches} inputMode="decimal" onChange={e=>setProjectedPitches(e.target.value)}/></label></div></div><div className="projection-kpis"><div><span>Projected K</span><strong>{sum("k").toFixed(2)}</strong></div><div><span>Projected BB</span><strong>{sum("bb").toFixed(2)}</strong></div><div><span>Projected HR</span><strong>{sum("hr").toFixed(2)}</strong></div><div><span>Projected BABIP</span><strong>{avgBabip.toFixed(3)}</strong></div><div><span>Vegas Outs</span><strong>{Number(vegasOuts||0).toFixed(1)}</strong></div></div><div className="projection-table"><table><thead><tr><th>#</th><th>Player</th><th>Hand</th><th>Exp K%</th><th>Exp BB%</th><th>Exp HR%</th><th>Exp BABIP</th><th>Proj PA</th><th>Park</th><th>HR PF</th><th>BABIP PF</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.player.playerId||i}><td>{i+1}</td><td className="player-name">{r.player.name}</td><td>{r.player.bats}</td><td>{fmtPct(r.k)}</td><td>{fmtPct(r.bb)}</td><td>{fmtPct(r.hr)}</td><td>{r.babip.toFixed(3)}</td><td>{r.pa}</td><td>{r.pf.park}{r.pf.fallback?" · avg":""}</td><td>{r.pf.hr.toFixed(2)}</td><td>{r.pf.babip.toFixed(2)}</td></tr>)}</tbody></table></div><div className="distribution-averages"><span>Distribution averages reserved for pitcher props</span><strong>K 4.79 · BB 1.72 · HR 0.71 · non-HR hits 4.17 · BABIP .290 · LOB 74.90%</strong></div></section>
}
