import {NextRequest,NextResponse} from "next/server";
export const dynamic="force-dynamic";
const DATE_PATTERN=/^\d{4}-\d{2}-\d{2}$/;const FG_CHALLENGE=/performing security verification|just a moment|cf-chl/i;
const easternToday=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/New_York",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
async function fetchJson(url:string){const response=await fetch(url,{headers:{Accept:"application/json","User-Agent":"Hallman-MLB-Model/1.0"},cache:"no-store"});if(!response.ok)throw new Error(`MLB data request failed (${response.status}).`);return response.json()}
async function checkFanGraphs(url:string){try{const response=await fetch(url,{headers:{Accept:"text/html","User-Agent":"Mozilla/5.0 (compatible; HallmanMLB/1.0)"},cache:"no-store",signal:AbortSignal.timeout(8000)});const text=await response.text();return response.ok&&!FG_CHALLENGE.test(text)?"available":"protected"}catch{return"unreachable"}}
function lineupFor(side:any,gameData:any){const players=side?.players||{};return(side?.battingOrder||[]).slice(0,9).map((id:number,index:number)=>{const player=players[`ID${id}`]||{},details=gameData?.players?.[`ID${id}`]||{};return{order:index+1,name:player.person?.fullName||details.fullName||"Unknown",bats:details.batSide?.code||"",position:player.position?.abbreviation||""}})}
function pitcherFor(game:any,side:"away"|"home"){const pitcher=game.gameData?.probablePitchers?.[side],details=pitcher?.id?game.gameData?.players?.[`ID${pitcher.id}`]:null;return{name:pitcher?.fullName||"TBD",throws:details?.pitchHand?.code||""}}
export async function GET(request:NextRequest){const date=request.nextUrl.searchParams.get("date")||easternToday();if(!DATE_PATTERN.test(date)||Number.isNaN(Date.parse(`${date}T12:00:00Z`)))return NextResponse.json({error:"Use a valid date in YYYY-MM-DD format."},{status:400});const sourceUrl=`https://www.fangraphs.com/scores?date=${date}`;try{const[fanGraphsStatus,schedule]=await Promise.all([checkFanGraphs(sourceUrl),fetchJson(`https://statsapi.mlb.com/api/v1/schedule?sportId=1&date=${date}`)]);const scheduled=schedule?.dates?.[0]?.games||[];const feeds=await Promise.all(scheduled.map((g:any)=>fetchJson(`https://statsapi.mlb.com/api/v1.1/game/${g.gamePk}/feed/live`).catch(()=>null)));const games=feeds.filter(Boolean).map((game:any)=>{const ap=pitcherFor(game,"away"),hp=pitcherFor(game,"home"),al=lineupFor(game.liveData?.boxscore?.teams?.away,game.gameData),hl=lineupFor(game.liveData?.boxscore?.teams?.home,game.gameData),firstPitch=new Date(game.gameData?.datetime?.dateTime);return{gamePk:game.gamePk,gameTime:Number.isNaN(firstPitch.getTime())?"TBD":firstPitch.toLocaleTimeString("en-US",{timeZone:"America/New_York",hour:"numeric",minute:"2-digit"})+" ET",venue:game.gameData?.venue?.name||"Venue TBD",status:game.gameData?.status?.detailedState||"Scheduled",away:{name:game.gameData?.teams?.away?.name||"Away",abbreviation:game.gameData?.teams?.away?.abbreviation||"AWY",pitcher:ap.name,throws:ap.throws,lineup:al,lineupStatus:al.length>=9?"Posted lineup":"Waiting for lineup"},home:{name:game.gameData?.teams?.home?.name||"Home",abbreviation:game.gameData?.teams?.home?.abbreviation||"HME",pitcher:hp.name,throws:hp.throws,lineup:hl,lineupStatus:hl.length>=9?"Posted lineup":"Waiting for lineup"}}});return NextResponse.json({date,fetchedAt:new Date().toISOString(),sourceUrl,fanGraphsStatus,source:fanGraphsStatus==="available"?"FanGraphs check + MLB live feed":"MLB live feed fallback",warning:fanGraphsStatus==="available"?"FanGraphs is reachable. Posted lineup details are normalized through MLB’s live game feed.":"FanGraphs protected the automated request, so posted lineups are being supplied by MLB’s official live feed. The dated FanGraphs link remains attached for verification.",games},{headers:{"Cache-Control":"public, max-age=60, stale-while-revalidate=300"}})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"The lineup feed is unavailable."},{status:502})}}
